theme: minima
title: "Raspberry Pi Bramble Home"
collections:
  site_content:
    output: true
    order:
      - 2024-03-12-bill-of-materials.md
      - 2024-03-12-assembly-instructions.md
      - 2024-03-26-OS-setup.md
      - 2024_03_29-install-munge.md
    sort_by: order
defaults:
  -
    scope: 
      path: ""
      type: "site_content"
    values:
      layout: "site_content"

sidebar:
  - label: "Steps"
    children:
      - bill-of-materials
      # - assembly-instructions
      # - os-setup
      # - shared-storage
      # - install-munge
      # - install-libaio
      # - install-ncurses
      # - install-mysql
  # - label: Menu Item with SubItems
  #   children: 
  #     - child-1-id
  #     - child-2-id

# permalink: /:categories/:year/:month/:day/:title:output_ext
